# Generated by Django 5.2.7 on 2025-11-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand_code', models.IntegerField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'brand_code')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.branch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('barcode_number', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('low_stock_threshold', models.PositiveIntegerField(default=0, help_text='Minimum stock level before alert/notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.branch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.organization')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.productgroup')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'barcode_number')},
            },
        ),
    ]
