# Generated by Django 5.2.7 on 2025-11-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0002_alter_user_organization'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_code',
            new_name='code',
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('organization', 'code')},
        ),
    ]
