# Generated by Django 5.2.7 on 2025-11-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_rename_brand_code_brand_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
