import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser


# ==========================================================
# ORGANIZATION (Tenant root)
# ==========================================================
class Organization(models.Model):
    """
    Represents the root entity for a tenant (organization).
    
    Attributes:
        id (UUIDField): Primary key, globally unique identifier.
        name (CharField): Unique, human-friendly name for the organization.
        code (CharField): Optional short code, globally unique, generated by services.
        created_at (DateTimeField): Timestamp when the organization was created.
    """
    #Step 0: Logo + Address section
    logo = models.ImageField(upload_to="org_logos/", null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True )
    
    # Step 1: Primary ID (UUID ensures uniqueness across all tenants)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Step 2: Unique name per tenant (used for display/logins)
    name = models.CharField(max_length=255, unique=True)

    # Step 3: Optional human-friendly code (globally unique, generated externally)
    code = models.CharField(max_length=20, unique=True, null=True, blank=True)

    #  Language preference for the org 
    LANGUAGE_CHOICES = [ 
        ("en", "English"), 
        ("bn", "বাংলা"), 
        ] 
    language = models.CharField( 
        max_length=5, 
        choices=LANGUAGE_CHOICES, 
        default="en", 
        help_text="Preferred language for this organization" )
    
    # Step 4: Audit field (auto-populated creation timestamp)
    created_at = models.DateTimeField(auto_now_add=True)

    # Step 5: String representation for admin/debugging
    def __str__(self):
        return self.name

    class Meta:
        # Step 6: Indexes for faster lookups by name and code
        indexes = [
            models.Index(fields=["name"]),
            models.Index(fields=["code"]),
        ]


# ==========================================================
# ORGANIZATION REQUEST (Controlled onboarding, auto-code)
# ==========================================================
class OrganizationRequest(models.Model):
    """
    Represents a pending request to create a new organization.
    
    Attributes:
        requested_name (CharField): Proposed organization name (unique).
        admin_username (CharField): Username of the first admin user.
        admin_email (EmailField): Email of the first admin user.
        admin_password (CharField): Password (hashed later in service).
        branch_name (CharField): Optional branch name for initial setup.
        notes (TextField): Optional notes for internal/admin use.
        status (CharField): Lifecycle status (pending, approved, rejected).
        created_at (DateTimeField): Timestamp when request was created.
        approved_at (DateTimeField): Timestamp when request was approved.
        rejected_at (DateTimeField): Timestamp when request was rejected.
    """
    # Optional address for the organization
    address = models.TextField(null=True, blank=True)
    # Optional logo for the organization
    logo = models.ImageField(upload_to='org_logos/', null=True, blank=True)
    # Step 1: Requested organization name (must be unique)
    requested_name = models.CharField(max_length=255, unique=True)

    #  Language preference for the org 
    LANGUAGE_CHOICES = [ 
        ("en", "English"), 
        ("bn", "বাংলা"), 
        ] 
    language = models.CharField( 
        max_length=5, 
        choices=LANGUAGE_CHOICES, 
        default="en", 
        help_text="Preferred language for this organization" )
    

    # Step 2: First admin user details
    admin_username = models.CharField(max_length=150)   # Initial admin username
    admin_email = models.EmailField()                   # Initial admin email
    admin_password = models.CharField(max_length=255)   # Stored hashed later

    # Step 3: Optional branch info for initial setup
    branch_name = models.CharField(max_length=255, null=True, blank=True)

    # Step 4: Notes for internal/admin use
    notes = models.TextField(null=True, blank=True)

    # Step 5: Status lifecycle (pending → approved/rejected)
    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("approved", "Approved"),
        ("rejected", "Rejected"),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")

    # Step 6: Audit trail timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    approved_at = models.DateTimeField(null=True, blank=True)
    rejected_at = models.DateTimeField(null=True, blank=True)

    # Step 7: String representation for admin/debugging
    def __str__(self):
        return f"{self.requested_name} ({self.status})"

    class Meta:
        # Indexes for faster queries by status, name, and email
        indexes = [
            models.Index(fields=["status"]),
            models.Index(fields=["requested_name"]),
            models.Index(fields=["admin_email"]),
        ]


# ==========================================================
# BRANCH (Optional subdivision; code unique per organization)
# ==========================================================
class Branch(models.Model):
    """
    Represents an optional subdivision under an organization.
    
    Attributes:
        organization (ForeignKey): Parent organization.
        name (CharField): Human-readable branch name.
        code (CharField): Branch code, unique per organization.
    """

    # Step 1: Link to parent organization
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name="branches")

    # Step 2: Human-readable branch name
    name = models.CharField(max_length=255)

    # Step 3: Branch code (unique within the organization)
    code = models.CharField(max_length=50, blank=True, null=True)

    # Step 4: String representation for admin/debugging
    def __str__(self):
        return f"{self.name} ({self.organization.name})"

    class Meta:
        # Step 5: Enforce uniqueness of branch code per organization
        unique_together = [("organization", "code")]

        # Step 6: Indexes for faster lookups by org/name/code
        indexes = [
            models.Index(fields=["organization", "name"]),
            models.Index(fields=["organization", "code"]),
        ]


# ==========================================================
# USER (Tenant + Platform Admin auth)
# ==========================================================
class User(AbstractUser):
    # Username is the login field — unique per org, NOT globally unique
    username = models.CharField(max_length=150)
    
    profile_image = models.ImageField(
        upload_to="profiles/",
        null=True,
        blank=True
    )
    phone = models.CharField(max_length=20, null=True, blank=True)

    # Email is kept for password reset / contact — unique per org, NOT globally unique
    email = models.EmailField()

    # Use username as the login identifier
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    # Role — matches migration 0006_alter_user_role exactly
    # DO NOT change choices without a new migration
    ROLE_CHOICES = [
        ('platform_admin', 'Platform Admin'),
        ('admin',          'Organization Admin'),
        ('manager',        'Inventory Manager'),
        ('employee',       'Employee'),
    ]
    role = models.CharField(
        max_length=20,
        choices=ROLE_CHOICES,
        default='employee',
    )

    organization = models.ForeignKey(
        'authenticate_app.Organization',
        on_delete=models.CASCADE,
        related_name="users",
        null=True, blank=True
    )

    branch = models.ForeignKey(
        'authenticate_app.Branch',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="users"
    )

    class Meta:
        # username unique per org, email unique per org — NOT globally unique
        unique_together = [
            ("username", "organization"),
            ("email", "organization"),
            ("phone", "organization"),
        ]


# ==========================================================
# LOGIN HISTORY (Tenant-aware audit)
# ==========================================================
class LoginHistory(models.Model):
    """
    Tracks user login activity with tenant context for auditing/security.
    
    Attributes:
        user (ForeignKey): User who logged in.
        organization (ForeignKey): Organization context.
        branch (ForeignKey): Optional branch context.
        ip_address (GenericIPAddressField): IP address of login.
        timestamp (DateTimeField): When the login occurred.
    """

    # Step 1: User who logged in
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Step 2: Tenant context (organization + optional branch)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True, blank=True)

    # Step 3: IP address of login
    ip_address = models.GenericIPAddressField()

    # Step 4: Timestamp of login
    timestamp = models.DateTimeField(auto_now_add=True)

    # Step 5: String representation for admin/debugging
    def __str__(self):
        return f"{self.user.username} | {self.organization.name} | {self.ip_address} | {self.timestamp}"

    class Meta:
        # Step 6: Indexes for faster queries by org/user/IP/timestamp
        indexes = [
            models.Index(fields=["organization", "timestamp"]),
            models.Index(fields=["user", "timestamp"]),
            models.Index(fields=["ip_address"]),
        ]