# Generated by Django 3.2.25 on 2026-03-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_stockreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='expires_at',
            field=models.DateTimeField(help_text='Reservation auto-expires after this time'),
        ),
    ]
