# Generated by Django 3.2.25 on 2026-03-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_auto_20260305_0917'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['organization', 'branch', 'expires_at'], name='reservation_cleanup_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['product', 'session_key', 'expires_at'], name='reservation_prod_sess_idx'),
        ),
    ]
