# Generated by Django 5.2.7 on 2025-11-23 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0003_user_phone_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('module', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate_app.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate_app.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'timestamp'], name='authenticat_organiz_9e1a0b_idx'), models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_ce5fa0_idx'), models.Index(fields=['activity_type'], name='authenticat_activit_4038d3_idx'), models.Index(fields=['module'], name='authenticat_module_2f4f9e_idx')],
            },
        ),
    ]
