# Generated by Django 5.2.7 on 2025-11-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0004_remove_user_timezone_user_profile_image_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
