# Generated by Django 5.2.7 on 2026-01-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0005_delete_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('admin', 'Organization Admin'), ('manager', 'Inventory Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
