# Generated by Django 5.2.7 on 2026-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', help_text='Preferred language for this organization', max_length=5),
        ),
        migrations.AddField(
            model_name='organizationrequest',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', help_text='Preferred language for this organization', max_length=5),
        ),
    ]
