# Generated by Django 3.2.25 on 2026-03-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0012_fix_username_login'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='authenticat_organiz_cd565f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='authenticat_organiz_5448bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='authenticat_role_cf8439_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
