# Generated by Django 3.2.25 on 2026-03-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0013_auto_20260319_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('phone', 'organization'), ('email', 'organization'), ('username', 'organization')},
        ),
    ]
